# Generated by Django 4.0.6 on 2022-08-07 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('fileID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=100)),
                ('file_type', models.CharField(default='doc', max_length=100)),
                ('fatherID', models.IntegerField(default=0)),
                ('content', models.TextField(max_length=65535, null=True)),
                ('isDelete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_modify_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'file',
            },
        ),
    ]
