# Generated by Django 4.0.3 on 2022-08-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='project',
        ),
        migrations.AddField(
            model_name='file',
            name='projectID',
            field=models.IntegerField(default=0),
        ),
    ]
