# Generated by Django 4.0.3 on 2022-08-03 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_img'),
        ('file', '0002_remove_file_project_file_projectid'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='team_perm',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='file',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
