# Generated by Django 4.0.3 on 2022-08-03 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_file_team_perm_alter_file_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='team_perm',
        ),
    ]
