# Generated by Django 4.0.3 on 2022-08-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_alter_file_file_type_alter_file_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_star',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(default='doc', max_length=100),
        ),
    ]
