# Generated by Django 4.0.6 on 2022-08-10 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('file', '0004_file_is_star_alter_file_file_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xml',
            fields=[
                ('xmlID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('xml_name', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=65535, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_modify_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
