# Generated by Django 4.0.3 on 2022-08-05 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_root_file'),
        ('file', '0004_remove_file_team_perm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='projectID',
        ),
        migrations.AddField(
            model_name='file',
            name='project',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='project.project'),
            preserve_default=False,
        ),
    ]
