# Generated by Django 4.0.6 on 2022-08-05 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prototype',
            fields=[
                ('prototypeID', models.AutoField(primary_key=True, serialize=False)),
                ('prototypeName', models.CharField(default='', max_length=64, verbose_name='原型名称')),
                ('prototypeUser', models.IntegerField(default=0, verbose_name='原型创建者')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='原型创建时间')),
                ('last_modify_time', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('projectID', models.IntegerField(default=0)),
                ('file_type', models.CharField(default='pro', max_length=100)),
                ('fatherID', models.IntegerField(default=0)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.team')),
            ],
            options={
                'db_table': 'prototype',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('pageID', models.AutoField(primary_key=True, serialize=False)),
                ('pageName', models.CharField(default='', max_length=64, verbose_name='页面名称')),
                ('pageComponentData', models.TextField(default='[]', verbose_name='页面组件信息')),
                ('pageCanvasStyle', models.TextField(default='[]', verbose_name='页面组件额外信息')),
                ('pageUser', models.IntegerField(default=0, verbose_name='页面创建者')),
                ('pageTime', models.DateTimeField(auto_now_add=True, verbose_name='页面创建时间')),
                ('is_first', models.BooleanField(default=False, verbose_name='是否为首页')),
                ('prototype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prototype.prototype')),
            ],
            options={
                'db_table': 'page',
            },
        ),
    ]
