# Generated by Django 4.0.6 on 2022-08-09 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('prototype', '0003_prototype_is_sharing'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageUse',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prototype.page')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'page_use',
            },
        ),
    ]
