# Generated by Django 4.0.3 on 2022-08-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='recently_used',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
