# Generated by Django 4.0.3 on 2022-08-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_team_recently_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='recently_used',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
