# Generated by Django 4.0.3 on 2022-08-03 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_team_user_is_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team_user',
            name='is_creator',
        ),
    ]
