# Generated by Django 4.0.6 on 2022-07-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=64, unique=True, verbose_name='用户名')),
                ('password', models.CharField(default='', max_length=32, verbose_name='密码')),
            ],
        ),
    ]
