# Generated by Django 4.0.3 on 2022-08-11 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_sharing',
            field=models.BooleanField(default=True),
        ),
    ]
