# Generated by Django 4.0.3 on 2022-08-05 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0005_remove_file_projectid_file_project'),
        ('project', '0002_project_root_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='root_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_root', to='file.file'),
        ),
    ]
