# Generated by Django 4.0.3 on 2022-08-01 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=64, verbose_name='用户名')),
                ('password', models.CharField(default='', max_length=32, verbose_name='密码')),
            ],
        ),
    ]
