# Generated by Django 4.0.6 on 2022-08-07 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=64, verbose_name='昵称')),
                ('password', models.TextField(default='', verbose_name='哈希密码')),
                ('real_name', models.CharField(default='', max_length=32, verbose_name='真实姓名')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='邮箱')),
                ('phone', models.CharField(default='', max_length=11, verbose_name='手机号')),
                ('profile', models.TextField(default='', verbose_name='个人简介')),
                ('img', models.CharField(default='', max_length=256, verbose_name='头像')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
