# Generated by Django 4.0.6 on 2022-08-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(default='', verbose_name='密码'),
        ),
    ]
