# Generated by Django 4.0.6 on 2022-08-01 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='user',
            name='identity',
            field=models.CharField(default='', max_length=64, verbose_name='身份'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='', max_length=11, verbose_name='手机号'),
        ),
        migrations.AddField(
            model_name='user',
            name='real_name',
            field=models.CharField(default='', max_length=32, verbose_name='真实姓名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=64, verbose_name='昵称'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
