# Generated by Django 4.0.6 on 2022-08-01 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.TextField(default='', verbose_name='个人简介'),
        ),
    ]
