# Generated by Django 4.0.6 on 2022-08-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img',
            field=models.CharField(default='https://xuemolan.oss-cn-hangzhou.aliyuncs.com/default.jpg', max_length=256, verbose_name='头像'),
        ),
    ]
