name: deploy backend to Aliyun and runserver
on:
  #监听push操作
  push:
    branches:
      - main
      - dev
jobs:
  # 任务ID
  build:
    # 运行环境
    runs-on: ubuntu-latest
    # 步骤
    steps:
    # 使用别人的action
    - uses: actions/checkout@v2
    # 步骤名称
    # 命名这个任务为发布Deploy
    - name: Deploy to Aliyun Server
      uses: easingthemes/ssh-deploy@v2.2.11
      with:
      # Private Key [public key should be add to the list of known hosts in .ssh of ALIYUN_REMOTE_USER] [pem format] [尝试放到root中]
        SSH_PRIVATE_KEY: ${{ secrets.ALIYUN_SERVER_ACCESS_TOKEN }}
      # Remote host
        REMOTE_HOST: ${{ secrets.ALIYUN_SERVER_HOST }}
      # Remote user
        REMOTE_USER: ${{ secrets.ALIYUN_REMOTE_USER }}
      # Remote port
        REMOTE_PORT: 22
      # Source directory
      #  SOURCE: "./"
      # Target directory
        TARGET: ${{ secrets.ALIYUN_TARGET }}
    - name: migrate DataBase and restart Django
      run: cd ${{ secrets.ALIYUN_TARGET }}
      
