name: deploy backend to Aliyun and runserver
on:
  #监听push操作
  push:
    branches:
      - main
      - dev
jobs:
  # 任务ID
  deploy:
    # 运行环境
    runs-on: ubuntu-latest
    # 步骤
    steps:
    # 使用别人的action
    - uses: actions/checkout@v2
    # 步骤名称
    # 命名这个任务为发布Deploy
    - name: Deploy to Aliyun Server
      uses: easingthemes/ssh-deploy@v2.2.11
      with:
      # Private Key
        SSH_PRIVATE_KEY: ${{ secrets.ALIYUN_SERVER_ACCESS_TOKEN }}
      # Remote host
        REMOTE_HOST: ${{ secrets.ALIYUN_SERVER_HOST }}
      # Remote user
        REMOTE_USER: ${{ secrets.ALIYUN_REMOTE_USER }}
      # Remote port
        REMOTE_PORT: 22
      # Target directory
        TARGET: ${{ secrets.ALIYUN_TARGET }}
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.ALIYUN_SERVER_HOST }}
          username: ${{ secrets.ALIYUN_REMOTE_USER }}
          key: ${{ secrets.ALIYUN_SERVER_ACCESS_TOKEN }}
          port: 22
          script: source ${{ ALIYUN_SHELL_SCRIPT_ADDRESS }}
      
